"""add earn_profile and earn_opportunity

Revision ID: 1bee44add331
Revises: a36eb9adbfd7
Create Date: 2026-05-28 10:59:07.881611

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1bee44add331"
down_revision: str | Sequence[str] | None = "a36eb9adbfd7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "earn_opportunity",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("opp_type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("brand_name", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "niche_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("min_tier", sa.String(length=16), nullable=False),
        sa.Column("commission_note", sa.String(length=120), nullable=True),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_earn_opp_active_type_tier",
        "earn_opportunity",
        ["is_active", "opp_type", "min_tier"],
        unique=False,
    )
    op.create_index(
        op.f("ix_earn_opportunity_min_tier"),
        "earn_opportunity",
        ["min_tier"],
        unique=False,
    )
    op.create_index(
        op.f("ix_earn_opportunity_opp_type"),
        "earn_opportunity",
        ["opp_type"],
        unique=False,
    )
    op.create_table(
        "earn_profile",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_earn_profile_user_id"), "earn_profile", ["user_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_earn_profile_user_id"), table_name="earn_profile")
    op.drop_table("earn_profile")
    op.drop_index(op.f("ix_earn_opportunity_opp_type"), table_name="earn_opportunity")
    op.drop_index(op.f("ix_earn_opportunity_min_tier"), table_name="earn_opportunity")
    op.drop_index("ix_earn_opp_active_type_tier", table_name="earn_opportunity")
    op.drop_table("earn_opportunity")
    # ### end Alembic commands ###
