"""add trending_articles table

Revision ID: 27bc25f94739
Revises: ff97c7faca57
Create Date: 2026-04-28 10:46:20.404271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27bc25f94739'
down_revision: Union[str, Sequence[str], None] = 'ff97c7faca57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trending_articles',
    sa.Column('url_hash', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('domain', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('velocity_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('url_hash')
    )
    op.create_index(op.f('ix_trending_articles_category'), 'trending_articles', ['category'], unique=False)
    op.create_index(op.f('ix_trending_articles_domain'), 'trending_articles', ['domain'], unique=False)
    op.create_index(op.f('ix_trending_articles_published_at'), 'trending_articles', ['published_at'], unique=False)
    op.create_index('ix_trending_category_published', 'trending_articles', ['category', 'published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trending_category_published', table_name='trending_articles')
    op.drop_index(op.f('ix_trending_articles_published_at'), table_name='trending_articles')
    op.drop_index(op.f('ix_trending_articles_domain'), table_name='trending_articles')
    op.drop_index(op.f('ix_trending_articles_category'), table_name='trending_articles')
    op.drop_table('trending_articles')
    # ### end Alembic commands ###
