"""restore personalization and trending tables

Revision ID: 2ae11fc42416
Revises: c7efed3e1588
Create Date: 2026-06-22 22:48:33.249952

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ae11fc42416"
down_revision: str | Sequence[str] | None = "c7efed3e1588"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trending_articles",
        sa.Column("url_hash", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("domain", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("velocity_score", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("url_hash"),
    )
    op.create_index(
        op.f("ix_trending_articles_category"),
        "trending_articles",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trending_articles_domain"),
        "trending_articles",
        ["domain"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trending_articles_published_at"),
        "trending_articles",
        ["published_at"],
        unique=False,
    )
    op.create_index(
        "ix_trending_category_published",
        "trending_articles",
        ["category", "published_at"],
        unique=False,
    )
    op.create_table(
        "user_personalization",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("nickname", sa.String(length=255), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("content_niche", sa.String(length=255), nullable=True),
        sa.Column("content_goal", sa.String(length=255), nullable=True),
        sa.Column("content_intent", sa.String(length=255), nullable=True),
        sa.Column("target_age_group", sa.String(length=255), nullable=True),
        sa.Column("target_country", sa.String(length=255), nullable=True),
        sa.Column("target_audience", sa.String(length=255), nullable=True),
        sa.Column("usp", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_personalization_user_id"),
        "user_personalization",
        ["user_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_personalization_user_id"), table_name="user_personalization"
    )
    op.drop_table("user_personalization")
    op.drop_index("ix_trending_category_published", table_name="trending_articles")
    op.drop_index(
        op.f("ix_trending_articles_published_at"), table_name="trending_articles"
    )
    op.drop_index(op.f("ix_trending_articles_domain"), table_name="trending_articles")
    op.drop_index(op.f("ix_trending_articles_category"), table_name="trending_articles")
    op.drop_table("trending_articles")
    # ### end Alembic commands ###
