"""add trending_articles table

Revision ID: 3d7a1740d6cc
Revises: b3c6bcb93ad6
Create Date: 2026-04-27 20:53:36.356226

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "3d7a1740d6cc"
down_revision: str | Sequence[str] | None = "b3c6bcb93ad6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
