"""add fk subscriptions.user_id -> users.id

Revision ID: 79d31d3d7a6d
Revises: 2ae11fc42416
Create Date: 2026-06-23 13:10:26.661153

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79d31d3d7a6d"
down_revision: str | Sequence[str] | None = "2ae11fc42416"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "subscriptions", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "subscriptions", type_="foreignkey")
    # ### end Alembic commands ###
