"""add creation_history table

Revision ID: a36eb9adbfd7
Revises: fb77b572cf8b
Create Date: 2026-05-24 12:15:47.823379

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a36eb9adbfd7"
down_revision: str | Sequence[str] | None = "fb77b572cf8b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "creation_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("target_platform", sa.String(length=32), nullable=False),
        sa.Column("tone", sa.String(length=32), nullable=True),
        sa.Column("variants", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_creation_history_user_id"),
        "creation_history",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_history_user_created",
        "creation_history",
        ["user_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_history_user_created", table_name="creation_history")
    op.drop_index(op.f("ix_creation_history_user_id"), table_name="creation_history")
    op.drop_table("creation_history")
    # ### end Alembic commands ###
