"""create_user_personalization_table

Revision ID: b3c6bcb93ad6
Revises: 9e622d521577
Create Date: 2026-03-28 14:12:14.662797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c6bcb93ad6'
down_revision: Union[str, Sequence[str], None] = '9e622d521577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Starting fresh: replace old `user_profiles` with `user_personalization`
    op.drop_index(op.f("ix_user_profiles_user_id"), table_name="user_profiles")
    op.drop_table("user_profiles")

    op.create_table(
        "user_personalization",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("nickname", sa.String(length=255), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("content_niche", sa.String(length=255), nullable=True),
        sa.Column("content_goal", sa.String(length=255), nullable=True),
        sa.Column("content_intent", sa.String(length=255), nullable=True),
        sa.Column("target_age_group", sa.String(length=255), nullable=True),
        sa.Column("target_country", sa.String(length=255), nullable=True),
        sa.Column("target_audience", sa.String(length=255), nullable=True),
        sa.Column("usp", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_personalization_user_id"),
        "user_personalization",
        ["user_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_personalization_user_id"),
        table_name="user_personalization",
    )
    op.drop_table("user_personalization")

    op.create_table(
        "user_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("field", sa.String(length=255), nullable=True),
        sa.Column("skills", sa.Text(), nullable=True),
        sa.Column("geography", sa.String(length=255), nullable=True),
        sa.Column("audience", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_profiles_user_id"),
        "user_profiles",
        ["user_id"],
        unique=True,
    )
    # ### end Alembic commands ###
