"""google login: nullable password + provider fields

Revision ID: fa402c40d6d7
Revises: 5a7ae15f1cbe
Create Date: 2026-06-24 10:40:36.445711

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa402c40d6d7"
down_revision: str | Sequence[str] | None = "5a7ae15f1cbe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default so existing rows satisfy NOT NULL (any pre-existing test
    # accounts default to "password"; new Google users set "google" in code).
    op.add_column(
        "users",
        sa.Column(
            "auth_provider",
            sa.String(length=32),
            nullable=False,
            server_default="password",
        ),
    )
    op.add_column(
        "users", sa.Column("provider_account_id", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users", sa.Column("avatar_url", sa.String(length=512), nullable=True)
    )
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.create_index(
        op.f("ix_users_provider_account_id"),
        "users",
        ["provider_account_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_provider_account_id"), table_name="users")
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_column("users", "avatar_url")
    op.drop_column("users", "provider_account_id")
    op.drop_column("users", "auth_provider")
    # ### end Alembic commands ###
