"""add social connections and insights tables

Revision ID: fb77b572cf8b
Revises: 27bc25f94739
Create Date: 2026-05-03 22:05:35.329404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb77b572cf8b'
down_revision: Union[str, Sequence[str], None] = '27bc25f94739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_user_id', sa.String(length=128), nullable=False),
    sa.Column('handle', sa.String(length=128), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.String(length=512), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=16), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform', name='uq_user_platform')
    )
    op.create_index(op.f('ix_social_connections_user_id'), 'social_connections', ['user_id'], unique=False)
    op.create_table('insights_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('total_content_count', sa.Integer(), nullable=False),
    sa.Column('total_views', sa.Integer(), nullable=False),
    sa.Column('total_engagement', sa.Integer(), nullable=False),
    sa.Column('follower_delta', sa.Integer(), nullable=False),
    sa.Column('views_delta', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['social_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'snapshot_date', name='uq_connection_date')
    )
    op.create_index(op.f('ix_insights_snapshots_connection_id'), 'insights_snapshots', ['connection_id'], unique=False)
    op.create_index('ix_snapshot_connection_date', 'insights_snapshots', ['connection_id', 'snapshot_date'], unique=False)
    op.create_table('top_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['social_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_top_content_connection_date_rank', 'top_content', ['connection_id', 'snapshot_date', 'rank'], unique=False)
    op.create_index(op.f('ix_top_content_connection_id'), 'top_content', ['connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_top_content_connection_id'), table_name='top_content')
    op.drop_index('ix_top_content_connection_date_rank', table_name='top_content')
    op.drop_table('top_content')
    op.drop_index('ix_snapshot_connection_date', table_name='insights_snapshots')
    op.drop_index(op.f('ix_insights_snapshots_connection_id'), table_name='insights_snapshots')
    op.drop_table('insights_snapshots')
    op.drop_index(op.f('ix_social_connections_user_id'), table_name='social_connections')
    op.drop_table('social_connections')
    # ### end Alembic commands ###
