"""add trending_articles table

Revision ID: ff97c7faca57
Revises: 3d7a1740d6cc
Create Date: 2026-04-27 21:21:40.440061

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ff97c7faca57"
down_revision: str | Sequence[str] | None = "3d7a1740d6cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
